name: Code analysis

on:
    workflow_call:
        
jobs:
    cargo-check:
        name: Check with cargo-check
        runs-on: ubuntu-24.04
        steps:
            - uses: ./.github/actions/setup-rust
            - run: cargo check
     
    cargo-clippy:
        name: Check with cargo-clippy
        runs-on: ubuntu-24.04
        steps:
            - uses: ./.github/actions/setup-rust
            - run: cargo clippy -- -D warnings
        
    cargo-fmt:
        name: Check with cargo-fmt
        runs-on: ubuntu-24.04
        steps:
            - uses: ./.github/actions/setup-rust
            - run: cargo fmt --all --check
            
    leptosfmt:
        name: Check with leptosfmt
        runs-on: ubuntu-24.04
        steps:
            - uses: ./.github/actions/setup-rust
            - run: cargo install --force leptosfmt
            - run: leptosfmt --check .